### ISSUE TITLE
How does this compare to previous approaches/

### ISSUE THREAD

**Issue by sje30** [pandoc-scholar/pandoc-scholar#1]
It's great to see this kind of package.  Can you say what it provides beyond current approaches, e.g. 
https://kieranhealy.org/blog/archives/2014/01/23/plain-text/ ?

**Comment by tarleb** [comment]
Apologies for the wait.  One of the main difference to Kieran Healy works (which are fantastic) is the focus on metadata and the fact that no external programs apart are required apart from `make` and `pandoc` itself.  I agree that this should be made clearer in the readme and will hence leave the issue open until I found the time to fix it. (And thanks again for the feedback on the preprint.)

**Comment by iandol** [comment]
What would also be cool would be to have an example markdown document + the commands needed + some final output examples (pdf, docx etc.). That would make it easier to assess what magic you are weaving with your Lua writers! 😸

**Comment by tarleb** [comment]
I finally got around to adding an overview section to the readme. It should help to convey the basic ideas behind this project.
