### ISSUE TITLE
remove fixltx2e from latex template, it is no longer required by tex

### ISSUE THREAD

**Issue by japhir** [pandoc-scholar/pandoc-scholar#10]
fixltx2e is not required since latex releases after 2015. https://www.ctan.org/pkg/fixltx2e?lang=en

**Comment by tarleb** [comment]
Thanks, wasn't aware of that. Does it cause a problem when left in? I'd rather be on the safe side and keep the template as backwards compatible as possible as long as it doesn't affect usability.

**Comment by japhir** [comment]
Apparently it now only throws an error message on compilation, so it shouldn't matter too much ;-).
