### ISSUE TITLE
Getting --smart/-S has been removed.  Use +smart or -smart extension instead

### ISSUE THREAD

**Issue by ghost** [pandoc-scholar/pandoc-scholar#12]
Not sure why, but getting the following error at compile time:

    pandoc --smart \
               -t C://Pandoc-scholar/writers/affiliations.lua \
               --output doc.enriched.json body.md
    --smart/-S has been removed.  Use +smart or -smart extension instead.
    For example: pandoc -f markdown+smart -t markdown-smart.
    Try pandoc --help for more information.
    make: ** [doc.enriched.json] Error 2

Using `pandoc-scholar` on a Windows 10 machine with `GnuWin32` .

Pandoc version is 2.0.6

**Comment by ghost** [comment]
Could it be because the option `--smart` has been removed since Pandoc 2.0, while it is still being used in the `pandoc-options.inc.mk` file at line [`PANDOC_READER_OPTIONS`](https://github.com/pandoc-scholar/pandoc-scholar/blob/3ff96a671a2e58325c2fd157f5d399e14abfde92/pandoc-options.inc.mk#L11)?

**Comment by ghost** [comment]
Adding `PANDOC_READER_OPTIONS =? -f markdown+smart` to the local Makefile seems to do the trick

**Comment by tarleb** [comment]
Thanks for the PR.  There are a few more issues with pandoc 2 which need fixing.  I'm looking into this.

Medium term, I intend to transition towards using pandoc's lua filters instead of our panlunatic-based work-around.

**Comment by ghost** [comment]
Thanks for the quick reply. I'll help with the lua filters if I can.

This and #13 seem to be sorted out (although I'm getting a new issue).
