### ISSUE TITLE
Discuss upstream integration?

### ISSUE THREAD

**Issue by katrinleinweber** [pandoc-scholar/pandoc-scholar#16]
Hello!

Has there been any discussion about pushing pandoc-scholar's features upstream to pandoc? It seems so useful, and I was surprised just now to find [no mention of for example CiTO semantic citations](https://github.com/jgm/pandoc/issues?q=cito) "up" there.

Cheers :-)

**Comment by tarleb** [comment]
Thank you for the kind words :)  I'm planning to modularize this a bit more, to factor out some Lua filters, and to push the most useful ones to the "official" [lua-filters](https://github.com/pandoc/lua-filters) repo. This should make CiTO functionallity easier to use without having to buy in to the full pandoc-scholar approach of wrapping pandoc and making it easier to use with rmarkdown/bookdown.

**Comment by tarleb** [comment]
Sorry for the long wait. The cito.lua filter has been added to the lua-filters repo and can now be used independently from the rest of pandoc-scholar: https://github.com/pandoc/lua-filters/tree/master/cito. Please let me know if you have ideas for further integration.

**Comment by katrinleinweber** [comment]
Not for now. Thank you so much for this :-)
