### ISSUE TITLE
Author and affiliation addresses

### ISSUE THREAD

**Issue by Michael-L-Miller** [pandoc-scholar/pandoc-scholar#19]
I would like add affiliation address to the title and author address to the corresponding author field (not just e-mail) and was wondering how this could be done.

**Comment by tarleb** [comment]
If I understand correctly, then you want to list the postal address for affiliations and corresponding authors. Adding an affiliation address for HTML output is quite simple, just adding an *address* field should be enough:

    institute:
      - fosg:
          name: ACME Corp.
          address: 23 Science Street, Eureka, Mississippi, USA

See `example/article.md` for an example.

For PDF output, this will require changes to the latex template (in file `templates/pandoc-scholar.latex`).  The details usually depend on the LaTeX document class that is used. Can you give more details of how and where you want the address to be shown?

**Comment by Michael-L-Miller** [comment]
Hi Dr. Krewinkel,

I figured it out.  Thanks for your help.
