### ISSUE TITLE
"--smart/-S has been removed" error

### ISSUE THREAD

**Issue by mgiugliano** [pandoc-scholar/pandoc-scholar#20]
Using pandoc 2.1.3 under macOS, the command

```
 make ARTICLE_FILE=example/article.md
```

fails and return the error:

```
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.
make: *** [outfile.enriched.json] Error 2
```

**Comment by tarleb** [comment]
Thanks for the report. The problem has already been fixed in the current master branch. If you can, please use the current git version. I'll make a new release once porting all scripts to pandoc 2 has been completed.
