### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by cristianvasquez** [pandoc-scholar/pandoc-scholar#26]
Hello, 

Any plans to make a Docker image for this? 

See:  https://users.soe.ucsc.edu/~ivo/_posts/2015-03-12-repeatable-paper-generation-with-docker-and-pandoc.html

Cristian

**Comment by tarleb** [comment]
Thanks for asking. I had thought about it, but wasn't sure if anybody would use it, as LaTeX containers tend to be huge. The linked article is very interesting in that regard. A docker container would also allow us to use more dependencies, e.g. pandoc-crossref.

Do you have specific requirements that you think should be met, like fonts or LaTeX packages?

**Comment by cristianvasquez** [comment]
I thought that a Docker-container could make it easy for others to generate documents without forcing them to install and configure things. But I guess that is more related to LaTeX than Pandoc.

My use case is just

1. To generate HTML and Epub
2. To run a script that extracts JsonLD from a bunch of documents.

I cannot find an example on how to output JsonLD though

**Comment by cagix** [comment]
Had a similar problem to make it easier for my colleagues to use my [Pandoc Lecture](https://github.com/cagix/pandoc-lecture) project. Maybe my [Docker file](https://github.com/cagix/pandoc-lecture/blob/master/docker/debianTexlive.df) based on Debian, TeXLive and Pandoc is a good place to start?

**Comment by tarleb** [comment]
@cristianvasquez About JSON-LD generation: getting the JSON-LD for the current article is possible by running `make outfile.jsonld`. Running that command should also show you the exact command that's executed, so you can adapt it to use in your own script.
If you need more help, hit me up by mail or on [gitter.im](https://gitter.im/pandoc-scholar/Lobby). I'll be happy to help (if time permits).

**Comment by tarleb** [comment]
Took a while, but we now have pandoc Docker images. This made it possible to generate pandoc-scholar images.

There is now a *pandocscholar* organization on Docker Hub. It has two repositories, `pandocscholar/alpine` and `pandocscholar/ubuntu`. The images are based off the respective pandoc images and have the same functionality.

The current development version is automatically published under the `:dev` tag; upcoming releases will also be automatically tagged and uploaded.

Recommended usage:

    docker run --rm --volume "$(pwd):/data" --user "$(id -u):$(id -g)" pandocscholar/alpine:dev
