### ISSUE TITLE
Title/subtitle field isn't printed in ODT/HTML file when it is formatted with latex

### ISSUE THREAD

**Issue by ivanhercaz** [pandoc-scholar/pandoc-scholar#29]
I am having an issue with the conversion of the title and subtitle field. Now that #28 is fixed, before to change it I check all the documents in all the formats. I am writing the subtitle with:

```latex
subtitle: \textit{subtitle}
```

The reason for this format is that I am using the subtitle field to write the title of the paper in English (original is in Spanish). If the title, or the subtitle, is written with this format it isn't printed in the ODT and HTML documents, but in the PDF is correct. In addition, I use this latex way to format the subtitle because I can't use markdown (`* *`) due it isn't fix the print of the field in both documents, and the PDF isn't printed fine at all (only print the body without the rest of the yaml fields).

So I ask you, could it be solved directly in the latex template used by Pandoc Scholar? I am thinking about this question, because it is possible that the best way is to create another conditional field in the latex template, like `titleEn`or `titleTranslated`, and give it the format in the template directly.

What do you think about? Does it happens for any special reason or it is directly inviable? 

One more time, thank you for your efforts and your work!

**Comment by tarleb** [comment]
The asterisks has a special meaning in YAML when it occurs at the beginning of a line ("YAML anchor" is a good term to search for if you are interested).  That's why `subtitle: *subtitle*` *won't* work. Quoting the string will fix this:

    subtitle: '*this should work fine*'

Bilingual documents are tricky, but pandoc has some support for it: setting the main document language using the `lang` metadata field, we then can mark spans and divs as being written in a different language. Example:

    ---
    lang: en
    ---

    Some latin: [Cogito ergo sum]{lang=la}

    Spanish wikipedia entry on pandoc:

    ``` {lang=es}
    Pandoc es un conversor de documentos libre y de código abierto, mayormente usado
    como una herramienta de escritura (especialmente por académicos), y es una base 
    para la publicación de flujos de trabajo.
    ```

This ensures that the appropriate quoting-style and hypenation is used for the selected language.

I'm not sure about adding additional support for translated titles etc to the template. It is a rather specialized use case which seems out of scope for pandoc scholar.

**Comment by ivanhercaz** [comment]
>The asterisks has a special meaning in YAML when it occurs at the beginning of a line ("YAML anchor" is a good term to search for if you are interested). That's why subtitle: *subtitle* won't work. Quoting the string will fix this:

You have learned me with that (YAML anchor) many another things of YAML, because I searched the term and I found [this simple but useful resource](https://learnxinyminutes.com/docs/yaml/) about YAML.

And yes, what I needed it was to quote the string, not with `' '`, but with `" " because I have one `'` inside the title.

> Bilingual documents are tricky, but pandoc has some support for it: setting the main document language using the lang metadata field, we then can mark spans and divs as being written in a different language.

I live very much the Pandoc support for multilingual documents, it works nice. My problem was how I was adding the main language of the document, as I told you in #30. Now everything works fine.

> I'm not sure about adding additional support for translated titles etc to the template. It is a rather specialized use case which seems out of scope for pandoc scholar.

Of course. What I meant was to try to create by my own the specific template, but adapted to Pandoc Scholar system. But to use `subtitle` is sufficient and useful, so I don't need to do it now.

One more time, thank you very much for your essential help!
