### ISSUE TITLE
possibly add scholarly-metadata as git submodule?

### ISSUE THREAD

**Issue by bdarcus** [pandoc-scholar/pandoc-scholar#3]
So `scholarly-metadata.inc.mk` setups the scholarly-metadata subdirectory, using curl on the repo release.

If you're using git to keep the local repo up-to-date, this is maybe a little counter intuitive (at least it was for me); perhaps include as a submodule?

**Comment by tarleb** [comment]
The problem is that scholarly-metadata depends on [panlunatic](https://github.com/tarleb/panlunatic) which in turn depends on [dkjson](https://github.com/LuaDist/dkjson). I tried to solve this by using [luarocks](https://luarocks.org) to resolve these dependencies. The scholarly-metadata archive is generated automatically for each release and already contains all required files.

I found the current solution to be simpler, but I'm open to changing this. Maybe including scholarly-markdown as a git subtree (saves the additional *submodule init* step) would be a good idea?

**Comment by iandol** [comment]
Just to mention that in #5 `curl` is broken for me in China, so this is a datapoint to consider in using curl for the dependency. For a naïve user, ideally there should be no dependencies and they should be able to download an archive with everything needed to run (apart from pandoc of course).

**Comment by tarleb** [comment]
> For a naïve user, ideally there should be no dependencies and they should be able to download an archive with everything needed to run (apart from pandoc of course).

We provide everything as ready-packed [tar.gz and zip archives](https://github.com/pandoc-scholar/pandoc-scholar/releases).  Is it possible to download those from within China?

**Comment by iandol** [comment]
Yes, the direct downloads appear fine, as is cloning the repository. But pandoc-scholar will not run without the scholarly-metadata dependency, and the curl download of the scholarly-metadata package hangs, breaking make from making anything. The workaround is to manually download https://github.com/pandoc-scholar/scholarly-metadata/releases/download/v1.1.0/scholarly-metadata.tar.gz directly and manually unarchive it to the correct directory. From this perspective providing the scholarly-metadata tools directly within the pandoc-scholar download would be more robust. Would the git submodule approach help for packaging in this case?

**Comment by tarleb** [comment]
Sorry for the sluggish replies, it's a busy week.

The scholarly-metadata files should already be included in the archive and the respective makefile target was intended for development only. It should never be triggered, and curl should not be necessary for normal users.  Could you provide some details of how you are invoking pandoc scholar?  Might be a path problem in pandoc scholar's makefiles.

**Comment by iandol** [comment]
Oh, this is actually my fault, when I last tested I used my cloned repo instead of my downloaded archive. I do see the archive version contains the scholarly-metadata files. I'll close my bug report then.

**Comment by tarleb** [comment]
I think having a self-contained repository is useful, and I ended up changing the repo to work with a simple `git clone`. Dependencies are now included via git-subtree (or added directly).  This allows us to track upstream, but avoids git submodules.

Thanks for your patience.
