### ISSUE TITLE
Access date isn't in the bibliography

### ISSUE THREAD

**Issue by ivanhercaz** [pandoc-scholar/pandoc-scholar#30]
I use web resources in the paper I am writting so I need something that I think should be mandatory to cite web resource: the access date to the resource. I use Zotero to manage my reference and to export it in [Better BibTeX](retorquere/zotero-better-bibtex) format to use it in the markdown file.

But I don't know why this parameter, which in my bib file is `urldate`, is not in the bibliography. In the bibliography what I see is "Retrieved from", but no the date. Have you any idea about it? Could it be an issue of Pandoc Scholar or could it be of Pandoc itself? I check the [APA style file](https://github.com/citation-style-language/styles/blob/master/apa.csl) I use and it is fine apparently.

P.S. Is there anyway in which I could translate the "Retrieve from" to the main language I use (Spanish)? In markdown file I have this:

```markdown
header-includes: |
  \usepackage[spanish]{babel}
```

But it doesn't seem to work with the bibliography.

**Comment by tarleb** [comment]
This is weird, `urldate` should work. Please try referencing the APA style file explicitly in your Markdown:

    ---
    csl: /path/to/apa.csl
    lang: es
    ---

This works for me with the latest versions of pandoc and pandoc-citeproc.

**Comment by ivanhercaz** [comment]
Thank you very much @tarleb! The main problem was the way in which I was specifying the language of the document:

```
header-includes: |
  \usepackage[spanish]{babel}
```

> Please try referencing the APA style file explicitly in your Markdown

This was what I thought it was strange, because everything is specified.Finally, the problem was the language setting and the solution was to change it to `lang: es`. It fixes the main issue (`urldate`) and the secondary issue (`text translated`).
