### ISSUE TITLE
--pdf-engine=lualatex not possible

### ISSUE THREAD

**Issue by ghost** [pandoc-scholar/pandoc-scholar#34]
I take the default github-folder with the example file "article.md".
Instead of `--pdf-engine=xelatex` in `pandoc-options.inc.mk` I changed it to `--pdf-engine=lualatex` but I receive `Error 43` and no PDF is produced.

Can you reproduce this behaviour? 
I do like to use `lualatex` for various reasons.

**Comment by tarleb** [comment]
That's weird. I tried on macOS but could not reproduce this. I can try on Linux later tonight. Which system are you on, and does pandoc return any more details? If not, could you add `--verbose` to `PANDOC_LATEX_OPTIONS`?

**Comment by ghost** [comment]
Thanks to `--verbose` I could track the error. It is due to the current bug in `microtype`.

I got rid of it by

```
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{luatexbase} % <<<< temporary bug-fix
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
```
