### ISSUE TITLE
use separate metadata-yaml file

### ISSUE THREAD

**Issue by ghost** [pandoc-scholar/pandoc-scholar#35]
I was wondering how I could use a separate yaml file with the metadata?
e.g. in my `makefile` `PANDOC_WRITER_OPTIONS = --metadata-file=data/metadata.yaml` doesn’t work.

**Comment by tarleb** [comment]
The metadata file is merged into the document during reading, so using `PANDOC_READER_OPTIONS` instead of `PANDOC_WRITER_OPTIONS` should work.

**Comment by ghost** [comment]
Unfortunately there is no difference with `PANDOC_READER_OPTIONS = --metadata-file data/metadata.yaml`

(Furthermore the lua-filter only works when I load it with `PANDOC_WRITER_OPTIONS  += --lua-filter=$(LUA_FILTERS_PATH)/short-captions/short-captions.lua`, which I guess is not the intended way?)

**Comment by ghost** [comment]
`PANDOC_READER_OPTIONS = data/metadata.yaml` is working.
