### ISSUE TITLE
author-info-blocks throws an error under pandoc 2.3.1

### ISSUE THREAD

**Issue by connorp** [pandoc-scholar/pandoc-scholar#41]
Attempting to use the `scholarly-metadata` and `author-info-blocks` lua filters with pandoc version 2.3.1—the version currently shipping with RStudio—(and version 2.2.3.1) throws an error in the latter:

```
Error running filter ../author-info-blocks/author-info-blocks.lua:
Error while running filter function: ../author-info-blocks/author-info-blocks.lua:168: attempt to call a nil value (method 'map')
```

Reproducible example: the `sample.md` file included with the `scholarly-metadata` filter. 

```
pandoc -f markdown sample.md -o sample.pdf --lua-filter=scholarly-metadata.lua --lua-filter=../author-info-blocks/author-info-blocks.lua
```

Any ideas?

**Comment by tarleb** [comment]
This is an issue with pandoc versions pre 2.4. See also pandoc/lua-filters#59 and pandoc/lua-filters#64. If you don't want to, or cannot, update, then just manually revert [this change](https://github.com/pandoc/lua-filters/commit/4b5018486dd7e6c3161d2da819b8455503d0d5c8).
