### ISSUE TITLE
Last author "and" does not appear in html output

### ISSUE THREAD

**Issue by pauliacomi** [pandoc-scholar/pandoc-scholar#45]
When compiling an html file, there does not appear to be an "and" before the last author. In the html template, a check exists for this:

```html
...
$for(author)$
  $if(author.last)$and $endif$<span property="author" typeof="Person">
...
```

But there there is no property `last` unless written manually. Was this supposed to be added in one of the lua filters?

Disclaimer: I am not very familiar with pandoc templates.

**Comment by tarleb** [comment]
Looks like this got lost at some point. If we'd require pandoc 2.10, then we could write

```
$if(author/allbutlast)$
$for(author/allbutlast)$
${it}$sep$,
$endfor$
 and
$endif$
${author/last}
$body$
```

That would be cleaner than having to set the `last` attribute in a filter. On the other hand, most people probably still use older versions, so better to use a different method.

**Comment by pauliacomi** [comment]
Good point, I missed that in the latest changelog. Unfortunately 2.10 should be avoided for now since `pandoc-xnos` is currently [broken](https://github.com/tomduck/pandoc-xnos/issues/16).

I have no experience with lua scripting, otherwise I'd try to fix it in a PR myself.

**Comment by pauliacomi** [comment]
Thanks!
