### ISSUE TITLE
is there any support for ORG markdown

### ISSUE THREAD

**Issue by aminevsaziz** [pandoc-scholar/pandoc-scholar#50]
org-mode markdown is powerful and is there any possibility to customize a bit the lua filters to be able support org syntax.
for example this an **org test file**

```
#+author: Arin^1,Arin^2
#+EMAIL: aa@aa.com, bb@bb.com
#+TITLE: Your title goes here
#+SUBTITLE: SUB goes here
#+INSTITUTE: aa, bb, cc
#+DESCRIPTION: This document catalogs a set of tips and tricks for composing documents in Org mode.
#+KEYWORDS:  org-mode, syntax, quick reference, cheat sheet, recommended practices, latex, beamer, html
#+PANDOC_OPTIONS: reference-doc:template.docx
#+PANDOC_OPTIONS: lua-filter:raw-block.lua lua-filter:abstract-to-meta.lua
```

and using a simple lua filter to extract EMAIL author INSTITUTE variables and insert them into META block
```

-- intermediate store for variables and their values
local variables = {}

--- Function called for each raw block element.
function RawBlock (raw)
  -- Don't do anything unless the block contains *org* markup.
  if raw.format ~= 'org' then return nil end

  -- extract variable name and value
  local name, value = raw.text:match '#%+(%w+):%s*(.+)$'
  if name and value then
    variables[name] = value
  end
end

-- Add the extracted variables to the document's metadata.
function Meta (meta)
  for name, value in pairs(variables) do
    meta[name] = value
  end
  return meta

```
however, im stuck bit due to lack extensive knowledge of lua and pandoc! any suggestions?

**Comment by tarleb** [comment]
It's definitely possible and would be a nice thing to have. I think it's out of scope for this project, so I'm closing the issue here.

I recommend the [pandoc-discuss mailing list](https://groups.google.com/g/pandoc-discuss) and [StackOverflow](https://stackoverflow.com) to get help with specific questions.
