### ISSUE TITLE
latex ⇨ PDF compile fails — ifsym error

### ISSUE THREAD

**Issue by iandol** [pandoc-scholar/pandoc-scholar#6]
Hi, trying to `make` the example and the latex conversion to PDF fails (I don't see a `latexmk` log using `make` so I ran `latexmk` directly on the `outfile.latex`):

```
kpathsea: Running mktexpk --mfmode / --bdpi 600 --mag 0+480/600 --dpi 480 ifsym10
mktexpk: /usr/local/texlive/2017basic/texmf-dist/web2c/mktexdir ./texlive/2017basic/texmf-var/fonts/pk/ljfour/public/ifsym failed.
kpathsea: Appending font creation commands to missfont.log.

xdvipdfmx:warning: Could not locate a virtual/physical font for TFM "ifsym10".
xdvipdfmx:warning: >> There are no valid font mapping entry for this font.
xdvipdfmx:warning: >> Font file name "ifsym10" was assumed but failed to locate that font.
xdvipdfmx:fatal: Cannot proceed without .vf or "physical" font for PDF output...

Output file removed.
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  xdvipdfmx: Command for 'xdvipdfmx' gave return code 256
```

Using MacTeX 2017basic, ifsym is installed.

**Comment by tarleb** [comment]
Huh, that's weird. I don't have a mac to test this on and am not familiar enough with that stack to guess what might causing it.

The only command we are using from the ifsym package is `\Letter` (renders as ✉), which marks corresponding authors.  If this is problematic, we could as well use a common glyph like *§*, which is supported by most fonts.

**Comment by iandol** [comment]
Perhaps `ifsym` requires some manual setup (the doc is in german); I only ever use XeLaTeX with opentype fonts as a blackbox from Pandoc to generate PDFs thus my LaTeX foo is weak. What was the problem with fontawesome?

**Comment by iandol** [comment]
I tried \textifsymbol{0} which doesn't work either. The font files are in the correct folders as far as I can tell (I tried to copy them to TEXMF-LOCAL), I tried un/reinstalling ifsym to no avail. Tried to search on that error but didn't find anything that helped...

**Comment by tarleb** [comment]
I was using fontawesome at first, but was worried that it's less common than ifsym. So no real issue here, I'll gladly switch back if it works better on Mac.

**Comment by iandol** [comment]
Well, I am an N of 1 so it could be a local problem on my machine. Fontawesome with XeLaTeX at least works on my machine....
