### ISSUE TITLE
Subscript not working

### ISSUE THREAD

**Issue by japhir** [pandoc-scholar/pandoc-scholar#7]
Hi! I've updated your template document to include some of the more common symbols and notations that I require for my articles. 

However, if I run your parser it doesn't successfully parse subscripts with the tilde symbol (e.g. `CO~2~`), but instead displays them normally in both html and pdf output, while the .latex file does have the proper `\textsubscript` tag. If I run plain pandoc manually, without the make file and your fancy lua parsers, it does parse the subscript correctly.

Example:

```
How does it handle 'quotes'? Are they nice and "curly"? What about
em-dashes---are they formatted correctly? And ranges? 5--12 should show me
what's what.

Can it do any superscripts^like\ this^? or subscripts~like\ this~?

Furthermore, I'm interested in *cursive* and **bold** and ***cursive bold?***
stuff.

And of course I want to know how it displays δ^13^C. Δ~47~? 

~2&nbsp;‰ VPDB. ~25.2(±3)&nbsp;℃

$x = \alpha x + \beta$

What about CO~2~? And CO~3~^2-^? 

Is this different from CO<sub>2</sub>? and CO<sub>3</sub><sup>2-</sup>?
Seems like latex doesn't pick it up then.

![Is this first figure numbered?](banana.jpg){#banana width=12cm}

see Fig. [1](#banana).

What about a table?

| these things | are all super | important |
|:-------------|:-------------:|----------:|
|  145         |             14|        oij|
| right?       | really        | though    |
```

Oh and by the way: is it possible to refer to figures the way we do it in LaTeX? Like `see Fig.~\ref{fig:banana}`, probably something like: `see Fig. [ref?](#banana)` such that it automatically creates a figure number?

**Comment by tarleb** [comment]
Hi Ilja,

thanks for the report.

Ilja Kocken <notifications@github.com> writes:
> However, if I run your parser it doesn't successfully parse subscripts with the
> tilde symbol (e.g. CO~2~), but instead displays them normally in both html and
> pdf output, while the .latex file does have the proper \textsubscript
> tag.

I was able to confirm this for HTML output (forgot to style `<sub>` and
`<sup>` elements) and will push a fix shortly.

I was unable to reproduce this with PDF output -- the tilde-based
subscript workes for me. The HTML-based subscript isn't expected to work
in PDF, as pandoc doesn't parse embedded HTML into its internal document
structure, but simply passes those tags through iff the output format
supports it (which LaTeX doesn't). So it seems that the custom HTML
template provided by pandoc-scholar is to blame.

> Oh and by the way: is it possible to refer to figures the way we do it in LaTeX?
> Like see Fig.~\ref{fig:banana}, probably something like: see Fig. [ref?]
> (#banana) such that it automatically creates a figure number?

Not yet, unfortunately. It's a long-standing pandoc issue. The best tool
for this is probably
[pandoc-crossref](https://github.com/lierdakil/pandoc-crossref). I
thought about including it in pandoc-scholar but didn't want to depend on an
additional binary other than pandoc/pandoc-citeproc.

**Comment by japhir** [comment]
Thanks Albert,

I see now that it did indeed work for .pdf. What wasn't working for pdf was the regular δ symbol, even though Δ was working (i.e., xelatex is picked up correctly). This might be because the upright delta symbol is not present in the regular font family, I've had to hack around with \usepackage{upgreek} and similar in earlier LaTeX documents.

The second missing feature is unfortunate, looks like I'll stick to plain latex or org-mode for now. Even though it is an extreme hassle to get co-authors their desired word track-changes versions.
Also, if I have to submit a specific LaTeX template, which usually won't allow new usepackage commands, this will not be usable.

Kind regards,

Ilja
