### ISSUE TITLE
Support more CiTO keywords?

### ISSUE THREAD

**Issue by LibrEars** [pandoc-scholar/pandoc-scholar#8]
Is there a reason why properties like http://purl.org/spar/cito/citesAsRecommendedReading are not supported?

Sincerely yours,
LibrEars

**Comment by tarleb** [comment]
It appears that this was an oversight on my part. Thanks for bringing it up, I'll fix it with the next release.

**Comment by LibrEars** [comment]
Cool,
thank you

**Comment by katrinleinweber** [comment]
The above PURL died because the GitHub repo seems to have changed structure. Maybe https://sparontologies.github.io/cito/current/cito.html#d4e217 is more persistent.

**Comment by tarleb** [comment]
Thanks @katrinleinweber . I intend to fix this while rewriting the base scripts to use pandoc Lua filters instead of our current custom writer based hack. I'm on it, but life keeps interfering.

**Comment by tarleb** [comment]
Pandoc-scholar now uses the CiTO support from [lua-filters](https://github.org/pandoc/lua-filters), which includes this keyword. I'll make a new release within the next days.

Thank you for your patience.

**Comment by katrinleinweber** [comment]
I thank _you_ for implementing this :-)

**Comment by LibrEars** [comment]
Awesome! I know with what I will write my PhD thesis.

**Comment by katrinleinweber** [comment]
Here's [an example toolchain](https://github.com/katrinleinweber/PhD-thesis/#toolchain-mixed-markdown--latex) ;-)

**Comment by tarleb** [comment]
I released the new version.

Wish you all the best for your thesis writing!
